stages:
- name: build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: ls
timeout: 60
notification:
  recipients:
  - recipient: '@lawrence'
    notifier: c-nfzzb:n-fmq4h
  condition:
  - Failed
