stages:
- name: build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: date
  - runScriptConfig:
      image: busybox
      shellScript: date
  - runScriptConfig:
      image: busybox
      shellScript: date
  when:
    branch: notest
- name: build2
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: date
    when:
      branch: test
  - runScriptConfig:
      image: busybox
      shellScript: date
    when:
      branch: notest
  - runScriptConfig:
      image: busybox
      shellScript: date
