stages:
- name: build
  steps:
  - applyAppConfig:
      catalogTemplate: p-ddj28:pcatalog-mysql
      version: 0.3.8
      answers:
        persistence.enabled: "false"
      name: mydb
      targetNamespace: default
timeout: 1
notification: {}
