stages:
- name: clone
  steps:
  - sourceCodeConfig:
      env:
        JAVA_OPTS: -Dorg.jenkinsci.plugins.gitclient.Git.timeOut=30
- name: build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: echo good
