stages:
- name: publish
  steps:
  - publishCatalogConfig:
      path: ./mychart
      catalog: memcached
      version: ${CICD_GIT_TAG}
      gitUrl: https://github.com/gitlawr/charts.git
      gitBranch: lawrtest
      gitAuthor: mytest
      gitEmail: test@example.com
    envFrom:
    - sourceName: publish-keys
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: publish-keys
      sourceKey: PASSWORD
      targetKey: PASSWORD
- name: deploy app
  steps:
  - applyAppConfig:
      catalog: lawrtest-memcached
      version: ${CICD_GIT_TAG}
      answers: |
        {
        "AntiAffinity": "soft",
        "defaultImage": "true",
        "image": "memcached",
        "imageTag": "1.5.6-alpine",
        "memcached.maxItemMemory": "64",
        "memcached.verbosity": "v",
        "replicaCount": "1",
        "metrics.enabled": "false",
        "showMemcachedOptions": "false"
        }
      name: myapp
      targetNamespace: myapp
    env:
      DEBUG: "true"
timeout: 60
