stages:
- name: clone
  steps:
  - sourceCodeConfig:
      skipClone: true
      skipTlsVerify: true
- name: build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: env
timeout: 60
