stages:
- name: build
  steps:
  - publishCatalogConfig:
      path: ./mychart
      catalogTemplate: memcached
      version: 0.1.0-${CICD_GIT_COMMIT}
      gitUrl: https://github.com/gitlawr/charts.git
      gitBranch: master
      gitAuthor: gitlawr
      gitEmail: test@example.com
    env:
      APP_VERSION: 1.5.6
      CATALOG_VERSION: 0.1.0-${CICD_GIT_COMMIT}
      CICD_SUBSTITUTE_VARS: APP_VERSION,CATALOG_VERSION
    envFrom:
    - sourceName: ghtoken
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: ghtoken
      sourceKey: PASSWORD
      targetKey: PASSWORD
notification: {}
