stages:
- name: build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: env
timeout: 60
notification:
  recipients:
  - recipient: lawrlee@foxmail.com
    notifier: lawrmail
  condition: ["Failed","Success"]