stages:
- name: build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: echo test
- name: publish-catalog
  steps:
  - publishCatalogConfig:
      path: ./charts/memcached/v2.0.4
      catalog: library/memcached
      version: v2.0.5
    envFrom:
    - sourceName: publish-key
      sourceKey: USERNAME
    - sourceName: publish-key
      sourceKey: PASSWORD
    - sourceName: publish-key
      sourceKey: DEPLOY_KEY
- name: apply-app
  steps:
  - applyAppConfig:
      catalog: library/memcached
      version: v2.0.4
      name: myapp
      targetNamespace: myappns
timeout: 60
