stages:
- name: build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: ls #stress -m 1 --vm-bytes 2G --vm-keep --timeout 10s
    cpuLimit: xxx
    cpuRequest: xxx
    memoryLimit: xxx
    memoryRequest: xxx 
