stages:
- name: clone
  steps:
  - sourceCodeConfig:
      skipTlsVerify: true
  when:
    branch: ne
- name: build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: env
timeout: 60
