stages:
- name: build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: ls
timeout: 60
notification:
  recipients:
  - recipient: lawrlee@foxmail.com
    notifier: test
  condition:
  - Failed
  - Success
