stages:
- name: build
  steps:
  - applyAppConfig:
      catalogTemplate: p-kq44f:pcatalog-mysql
      version: 0.3.8
      answers:
        persistence.enabled: "false"
      name: mydb2
      targetNamespace: default
