stages:
- name: build
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-mysql
      version: 0.3.8
      answers:
        persistence.enabled: "false"
      name: mytest
      targetNamespace: default
timeout: 60
notification: {}
