stages:
- name: build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: date
  - runScriptConfig:
      image: busybox
      shellScript: date
  - runScriptConfig:
      image: busybox
      shellScript: date
