stages:
- name: build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: date
  when:
    branch: {}
- name: apply
  steps:
  - applyYamlConfig:
      path: ./sm.yml
notification: {}
