stages:
- name: clone
  steps:
  - sourceCodeConfig:
      skipTlsVerify: true
  when:
    branch:
      include:
      - ne
- name: build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: env && ls
timeout: 60
