stages:
- name: build
  steps:
  - publishCatalogConfig:
      path: ./mychart
      catalogTemplate: memcached
      version: 0.1.0_${CICD_GIT_COMMIT}
      gitUrl: http://52.221.241.67:8929/root/charts.git
      gitBranch: master
      gitAuthor: lawr
      gitEmail: lawr@example.com
    envFrom:
    - sourceName: publish-keys
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: publish-keys
      sourceKey: PASSWORD
      targetKey: PASSWORD
timeout: 1
notification: {}
