stages:
- name: publish
  steps:
  - publishCatalogConfig:
      path: ./mychart
      catalog: memcached
      version: ${CICD_GIT_COMMIT}
      gitUrl: https://github.com/gitlawr/charts.git
      gitBranch: lawrtest
      gitAuthor: mytest
      gitEmail: test@example.com
    envFrom:
    - sourceName: publish-keys
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: publish-keys
      sourceKey: PASSWORD
      targetKey: PASSWORD
- name: deploy app
  steps:
  - applyAppConfig:
      catalog: lawrtest-memcached
      version: 2.3.1
      answers: '{"a":"b"}'
      name: myapp
      targetNamespace: myapp
timeout: 60
