stages:
- name: build
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-grafana
      version: 0.0.31
      name: graf
      targetNamespace: default
    envFrom:
      - sourceName: api-key
        sourceKey: API_TOKEN
        targetKey: API_TOKEN
notification: {}
