stages:
- name: clone
  steps:
  - sourceCodeConfig: {}
    env:
      HTTP_PROXY: http://13.251.127.172:8888
      HTTPS_PROXY: http://13.251.127.172:8888
- name: build
  steps:
  - runScriptConfig:
      image: lawr/kubectl
      shellScript: env
timeout: 1
notification: {}
