stages:
- name: build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: echo good
notification:
  recipients:
  - recipient: '@lawrence'
    notifier: c-dmjzz:n-vkd96
  - recipient: '@lawrence'
    notifier: c-dmjzz:n-nfjfw
  condition:
  - Success
  - Failed
