stages:
- name: clone
  steps:
  - sourceCodeConfig: {}
    env:
      HTTP_PROXY: http://13.251.127.172:8888
      HTTPS_PROXY: http://13.251.127.172:8888
- name: build
  steps:
  - runScriptConfig:
      image: lawr/kubectl
      shellScript: env
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: mytest:v1
      registry: 127.0.0.1:34345
    env:
      HTTP_PROXY: http://13.251.127.172:8888
      HTTPS_PROXY: http://13.251.127.172:8888
timeout: 1
notification: {}
