stages:
- name: build
  steps:
  - runScriptConfig:
      image: lawr/kubectl
      shellScript: env
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: mytest:v1
      registry: 127.0.0.1:34345
timeout: 1
notification: {}
