stages:
- name: build
  steps:
  - publishCatalogConfig:
      path: ./charts/memcached/latest
      catalogTemplate: memcached
      version: 2.3.1-${CICD_GIT_COMMIT}
      gitUrl: https://github.com/gitlawr/charts.git
      gitBranch: lawrtest
      gitAuthor: gitlawr
      gitEmail: lawrleegle@gmail.com
    envFrom:
    - sourceName: publish-keys
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: publish-keys
      sourceKey: PASSWORD
      targetKey: PASSWORD
timeout: 60
notification: {}
