stages:
- name: build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: ls
timeout: 60
notification:
  recipients:
  - recipient: 李平辉
    notifier: c-kr9gr:n-nnp6f
  condition:
  - Success
  - Changed
  - Failed
