name: Test Docker Tags
on:
  workflow_dispatch:
  push:

jobs:
  publish-docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Get Metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: foo/bar
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=pep440,pattern={{raw}}
            type=pep440,pattern=v{{major}}.{{minor}},enable=${{ startsWith(github.ref, 'refs/tags/') && !contains(github.ref, 'rc') }}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') && !contains(github.ref, 'rc') }}
          # set no tag suffix for cuda as the default, set -{device} suffix for others
          flavor: |
            latest=false
            suffix=${{ '-the-suffix' }}
